version: '2'
services:
  web:
    build: .
    container_name: pokket-voting-server
    command: yarn run start
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "8081:8080"
    links:
      - db
    depends_on:
      - db
  db:
    image: rethinkdb
    container_name: pokket-voting-db
    ports:
      - "58080:8080"
      - "28015:28015"
      - "29015:29015"